pipeline:
  build:
    image: ubuntu:xenial
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - DEBIAN_FRONTEND=noninteractive
    commands:
      - apt-get update -qq -y
      - apt-get install -y --no-install-recommends apt-utils  > /dev/null
      - apt-get -y install sudo > /dev/null
      # Install Snapcraft from Git to use the yaml
      # merge tag feature which was not yet shipped
      # in a stable Snapcraft release.
      #- apt-get install -y snapcraft > /dev/null
      - apt-get install -y git build-essential squashfs-tools libffi-dev libsodium-dev > /dev/null
      - apt-get install -y libapt-pkg-dev libarchive13 python3 python3-dev python3-pip > /dev/null
      - git clone -q https://github.com/snapcore/snapcraft .snapcraft-repo > /dev/null
      - pip3 install --upgrade pip > /dev/null
      - cd .snapcraft-repo
      - git checkout 0cb9b0532e90c3cbfd5ff0fa5bb670d5cb4f0c1c > /dev/null
      - pip3 install -r requirements.txt . > /dev/null
      - ln -s /usr/local/share/snapcraft /usr/share/snapcraft
      - cd ..
      - rm -rf .snapcraft-repo
      # Snapcraft: only print the last 100 lines of output
      - snapcraft snap -o liri-platform0.snap | tail -n 100
      # Fix pkg-config files prefix
      # to point to /snap/liri-platform0/current
      # FIXME: Find a better solution for this:
      # If possible, moving this to snapcraft.yaml
      # in some form would be much better.
      - unsquashfs -d snap-root liri-platform0.snap
      - find snap-root -type f -name "*.pc" -exec sed -i "s|^prefix=.*|prefix=/snap/liri-platform0/current|" "{}", \;
      - mksquashfs snap-root liri-platform0.snap -noappend -comp xz -no-xattrs -all-root
      - rm -rf snap-root
